name: Bhoraskar Hospital
url: http://www.bhoraskar.com

exclude: [README.md, Makefile]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables]

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Base pathname for links.
base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Contact
      link: /contact
    - title: Facilities
      link: /facilities

# Addons
gems:
  - jekyll-redirect-from

