name: Bhoraskar Hospital
url: http://www.bhoraskar.com

exclude: [README.md, Makefile]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables]

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Contact
      link: /contact
    - title: Specialists
      link: /specialists
    - title: Facilities
      link: /facilities
    - title: ENT Section
      link: /ent/earcaretips.html

# Addons
gems:
  - jekyll-redirect-from

