name: Bhoraskar Hospital
url: http://bhoraskar.github.io

exclude: [README.md]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables]

# colorize code snippets with the pygment module
pygments: true

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Base pathname for links.
base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Facilities
      link: /facilities.html
    - title: Specialists
      link: /specialists.html
    - title: ENT Section
      link: /ent.html
    - title: OBGY Section
      link: /obgy.html
    - title: Contact
      link: /contact.html
# Addons
gems:
  - jekyll-redirect-from

