name: Bhoraskar Hospital
url: http://www.bhoraskar.com

exclude: [README.md, Makefile]

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Contact
      link: /contact
    - title: Specialists
      link: /specialists
    - title: Facilities
      link: /facilities
    - title: ENT
      link: /ent/earcaretips.html
    - title: OBGY
      link: /obgy/pregnant.html

# Addons
gems:
  - jekyll-redirect-from

